apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - namespace.yaml
  - ../../base

images:
  - name: docker.pdlab.dev/portfolio
    newTag: main-latest
